import React, { useEffect, useRef, useState } from 'react';
import { AppIcon, Icon } from './Icon';
import { AppId, appNames, apps, Mode, useSystemContext, WindowState } from './state';
import { Application, Dock } from './Shell';
import { AboutMeWidget, CertificationsWidget, ClockWidget, GithubWidget, NeofetchWidget, NotesWidget, TelemetryWidget } from './Widgets';

function Apple() { return <svg width="16" height="19" viewBox="0 0 24 28" fill="currentColor" aria-hidden="true"><path d="M17 1c.2 3-2.2 5.6-5 5.5C11.8 4 14 1.4 17 1ZM20 16c0 4 3 5 3 5s-2.2 6-5.7 6c-1.6 0-2.4-1-4.3-1s-3 1-4.5 1C5.1 27 1 20.6 1 15.2 1 10.7 3.6 8 7 8c2 0 3.5 1.2 5 1.2S15.2 8 17.4 8c2.3 0 4.3 1.2 5.6 3-2.2 1.2-3 3-3 5Z"/></svg>; }
function MenuBar() {
  const s = useSystemContext(); const [menu, setMenu] = useState(''); const menuRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!menu) return; const dismiss = (e: PointerEvent) => { if (!menuRef.current?.contains(e.target as Node)) setMenu(''); }; const escape = (e: KeyboardEvent) => { if (e.key === 'Escape') setMenu(''); }; document.addEventListener('pointerdown', dismiss); document.addEventListener('keydown', escape); return () => { document.removeEventListener('pointerdown', dismiss); document.removeEventListener('keydown', escape); }; }, [menu]);
  const commands: Record<string, { label: string; action: () => void }[]> = {
    Apple: [{ label: 'About this portfolio', action: () => s.open('about') }, { label: 'System Settings…', action: () => s.open('settings') }, { label: 'Force quit active app', action: () => { if (s.active) s.close(s.active); } }, { label: 'Sleep', action: () => s.setSleeping(true) }, { label: 'Restart workspace', action: () => { s.windows.forEach(w => s.close(w.id)); s.home(); s.notify('Workspace restarted. Preferences preserved.'); } }],
    File: [{ label: 'Open Projects', action: () => s.open('projects') }, { label: 'New Terminal', action: () => s.open('terminal') }, { label: 'New Message', action: () => s.open('mail') }],
    Edit: [{ label: 'Copy portfolio link', action: () => { navigator.clipboard?.writeText(location.href).then(() => s.notify('Portfolio link copied')).catch(() => s.notify('Clipboard unavailable')); } }, { label: 'Edit quick note', action: () => { (document.querySelector('[aria-label="Quick note"]') as HTMLTextAreaElement)?.focus(); } }],
    View: [{ label: 'Toggle appearance', action: () => s.setTheme(s.theme === 'dark' ? 'light' : 'dark') }, { label: 'Show desktop', action: () => { s.windows.forEach(w => s.updateWindow(w.id, { minimized: true })); s.home(); } }, { label: 'Toggle full screen', action: () => { const active = s.windows.find(w => w.id === s.active); if (active) s.updateWindow(active.id, { maximized: !active.maximized }); } }],
    Window: apps.map(id => ({ label: appNames[id], action: () => s.open(id) })),
    Help: [{ label: 'Keyboard shortcuts', action: () => s.notify('⌘/Ctrl K: Recruiter Brief · Shift+⌘/Ctrl K: Search · Escape: Back · ⌘/Ctrl ,: Settings') }, { label: 'About Zakarya', action: () => s.open('about') }],
  };
  return <div className="menu-bar" ref={menuRef}><div className="menu-left"><button className="apple-menu" aria-label="Apple menu" aria-expanded={menu === 'Apple'} onClick={() => setMenu(menu === 'Apple' ? '' : 'Apple')}><Apple/></button><strong>{s.active ? appNames[s.active] : 'Finder'}</strong>{['File', 'Edit', 'View', 'Window', 'Help'].map(item => <button key={item} aria-expanded={menu === item} onClick={() => setMenu(menu === item ? '' : item)}>{item}</button>)}</div><button className="recruiter-pill menu-brief" onClick={s.startBrief}>⚡ Recruiter Brief <span>(60s)</span></button><div className="menu-right"><button className="soc-menu-alert" title="Simulated SOC alert: Suspicious beaconing from 192.168.1.105" onClick={() => s.open('defense')}><i/> SOC Alert <span>· 192.168.1.105</span></button><button className="sound-toggle" aria-pressed={s.soundOn} onClick={s.toggleSound}>{s.soundOn ? 'Sound On' : 'Mute'}</button><span className="battery-status" title={s.battery ? 'Device battery' : 'Battery information unavailable'}>{s.battery ? `${s.battery.level}%` : '—'}<Icon name={s.battery?.charging ? 'bolt' : 'battery'} size={20}/></span><button aria-label="Network controls" onClick={() => s.setShade(!s.shade)}><Icon name="wifi" size={17}/></button><button aria-label="Spotlight search" onClick={() => s.setSpotlight(!s.spotlight)}><Icon name="search" size={16}/></button><button aria-label="Control Center" onClick={() => s.setShade(!s.shade)}><Icon name="control" size={17}/></button><span className="menu-date">{s.time.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' })}</span><time>{s.time.toLocaleTimeString('en-GB')}</time></div>{menu && <div className="system-menu" role="menu" style={{ left: menu === 'Apple' ? 12 : 115 + ['File', 'Edit', 'View', 'Window', 'Help'].indexOf(menu) * 43 }}>{commands[menu].map(c => <button role="menuitem" key={c.label} onClick={() => { c.action(); setMenu(''); }}>{c.label}</button>)}</div>}</div>;
}
function Window({ state }: { state: WindowState }) {
  const s = useSystemContext(); const node = useRef<HTMLElement>(null); const drag = useRef({ x: 0, y: 0, wx: 0, wy: 0, down: false });
  useEffect(() => { const resize = () => { const el = node.current; if (!el || state.maximized) return; const r = el.getBoundingClientRect(); const dx = Math.min(0, window.innerWidth - 80 - r.left); const dy = Math.min(0, window.innerHeight - 125 - r.top); if (dx || dy) s.updateWindow(state.id, { x: Math.max(-20, state.x + dx), y: Math.max(-25, state.y + dy) }); }; window.addEventListener('resize', resize); return () => window.removeEventListener('resize', resize); }, [state]);
  return <section ref={node} aria-label={`${appNames[state.id]} window`} className={`app-window ${s.brief && ['dossier', 'flagships', 'quickstart'].includes(state.id) ? 'brief-tile' : ''} window-${state.id} ${state.maximized ? 'maximized' : ''} ${state.minimized ? 'minimized' : ''} ${s.active === state.id ? 'focused' : ''}`} style={{ '--window-x': `${state.x}px`, '--window-y': `${state.y}px`, zIndex: state.z + 10 } as React.CSSProperties} onPointerDownCapture={() => { if (s.active !== state.id) s.focus(state.id); }}><header className="window-titlebar" onDoubleClick={e => { if (!(e.target as HTMLElement).closest('button')) s.updateWindow(state.id, { maximized: !state.maximized }); }} onPointerDown={e => { if ((e.target as HTMLElement).closest('button') || state.maximized || (s.brief && ['dossier', 'flagships', 'quickstart'].includes(state.id))) return; drag.current = { x: e.clientX, y: e.clientY, wx: state.x, wy: state.y, down: true }; e.currentTarget.setPointerCapture(e.pointerId); s.focus(state.id); }} onPointerMove={e => { if (!drag.current.down || !node.current) return; const r = node.current.getBoundingClientRect(); const baseX = r.left - state.x, baseY = r.top - state.y; s.updateWindow(state.id, { x: Math.max(8 - baseX, Math.min(window.innerWidth - 80 - baseX, drag.current.wx + e.clientX - drag.current.x)), y: Math.max(35 - baseY, Math.min(window.innerHeight - 130 - baseY, drag.current.wy + e.clientY - drag.current.y)) }); }} onPointerUp={() => { drag.current.down = false; }} onPointerCancel={() => { drag.current.down = false; }}><div className="traffic-lights"><button aria-label={`Close ${appNames[state.id]} window`} className="traffic-close" onClick={() => s.close(state.id)}>×</button><button aria-label={`Minimize ${appNames[state.id]} window`} className="traffic-minimize" onClick={() => { s.minimize(state.id); }}>−</button><button aria-label={`Maximize ${appNames[state.id]} window`} className="traffic-maximize" onClick={() => s.updateWindow(state.id, { maximized: !state.maximized })}>+</button></div><span><Icon name={state.id} size={13}/>{appNames[state.id]}<span className="title-divider">—</span>Zakarya</span><button className="window-more" aria-label="Search apps" onClick={() => s.setSpotlight(true)}><Icon name="search" size={15}/></button></header><div className="window-content"><Application id={state.id}/></div></section>;
}
export function Desktop() {
  const s = useSystemContext();
  const visibility = s.config?.widgets?.visibility || {
    about: true,
    certs: true,
    github: true,
    neofetch: true,
    telemetry: false,
    clock: false,
    notes: false
  };

  const widgets: Record<string, React.ReactNode> = { about: <AboutMeWidget/>, certs: <CertificationsWidget/>, github: <GithubWidget/>, neofetch: <NeofetchWidget/>, clock: <ClockWidget/>, telemetry: <TelemetryWidget/>, notes: <NotesWidget/> };
  const order: string[] = s.config?.widgets?.order || Object.keys(widgets);
  return <><MenuBar/><div className="desktop-label"><span className="desktop-brand">z<span>.</span></span><span>PERSONAL WORKSPACE <i/> MADE TO EXPLORE</span></div><div className="desktop-mode-switch">{(['macos', 'ios', 'android'] as Mode[]).map(m => <button key={m} className={s.mode === m ? 'selected' : ''} onClick={() => s.setMode(m)}><Icon name={m === 'macos' ? 'monitor' : 'phone'} size={14}/>{m === 'macos' ? 'macOS' : m === 'ios' ? 'iOS' : 'Android'}</button>)}</div><div className="desktop-widgets">{[...new Set([...order, ...Object.keys(widgets)])].filter(id => visibility[id]).map(id => <React.Fragment key={id}>{widgets[id]}</React.Fragment>)}</div><div className="desktop-shortcuts">{(['projects', 'terminal', 'settings', 'mail'] as AppId[]).map(id => <button key={id} onClick={() => s.open(id)}><AppIcon id={id}/><span>{appNames[id]}</span></button>)}</div>{s.windows.map(w => <Window key={w.id} state={w}/>)}<div className="desktop-signature"><i className="status-dot"/> Available for what's next<span>Built with intention.</span></div><Dock/></>;
}
