import React from 'react';

function Field({ label, value, onChange, type = 'text', placeholder = '' }: { label: string; value: string | number; onChange: (value: string) => void; type?: string; placeholder?: string }) {
  return <label className="admin-field"><span>{label}</span><input className="admin-input" type={type} value={value ?? ''} placeholder={placeholder} onChange={e => onChange(e.target.value)}/></label>;
}
export function CommandCenterAdmin({ data, setData, section }: { data: any; setData: (data: any) => void; section: string }) {
  const update = (key: string, patch: object) => setData({ ...data, config: { ...data.config, [key]: { ...data.config[key], ...patch } } });
  const certs = data.config.widgets?.certs || [];
  const cert = (id: string, patch: object) => update('widgets', { certs: certs.map((c: any) => c.id === id ? { ...c, ...patch } : c) });
  const order: string[] = data.config.widgets?.order || ['about','certs','neofetch','github','clock','telemetry','notes'];
  const move = (index: number, direction: number) => { const next = [...order]; [next[index], next[index + direction]] = [next[index + direction], next[index]]; update('widgets', { order: next }); };
  if (section === 'appearance') return <section className="admin-card command-admin"><h2>Recruiter brief & contact</h2><p>These seeded fields appear in the executive dossier. Leave links empty until you have the real URLs.</p><div className="admin-form-grid">{[
    ['degree','Degree / current study'],['focus','Security focus'],['email','Interview email'],['bookingUrl','Interview booking URL'],['resumeUrl','Resume PDF URL'],['philosophy','Cybersecurity philosophy'],['whyHire','Why hire Zakarya?']
  ].map(([key,label]) => <Field key={key} label={label} value={data.config.recruiter?.[key] || ''} type={key === 'email' ? 'email' : 'text'} onChange={value => update('recruiter', { [key]: value })}/> )}</div><h3>Cinematic transition clips</h3><p>Use a local asset path or HTTPS video URL. Videos honor reduced motion and can be skipped with Escape or Skip button.</p><div className="admin-form-grid"><Field label="macOS → iOS video" value={data.config.media?.macosToIos || ''} onChange={value => update('media', { macosToIos: value })}/><Field label="iOS → macOS video (Rewind)" value={data.config.media?.iosToMacos || ''} onChange={value => update('media', { iosToMacos: value })}/><Field label="macOS → Android video" value={data.config.media?.macosToAndroid || ''} onChange={value => update('media', { macosToAndroid: value })}/><Field label="Android → macOS video (Rewind)" value={data.config.media?.androidToMacos || ''} onChange={value => update('media', { androidToMacos: value })}/><Field label="iOS → Android video" value={data.config.media?.iosToAndroid || ''} onChange={value => update('media', { iosToAndroid: value })}/></div></section>;
  if (section !== 'widgets') return null;
  return <section className="admin-card command-admin"><h2>Desktop order & credential status</h2><p>Reorder desktop cards. Visibility and content controls are below.</p><div className="admin-widget-order">{order.map((id,i) => <div key={id}><strong>{id}</strong><button className="admin-secondary-btn" aria-label={`Move ${id} widget up`} disabled={!i} onClick={() => move(i,-1)}>↑</button><button className="admin-secondary-btn" aria-label={`Move ${id} widget down`} disabled={i === order.length - 1} onClick={() => move(i,1)}>↓</button></div>)}</div><h3>Credential publishing</h3>{certs.map((c: any) => <div key={c.id} className="admin-credential-status"><strong>{c.title}</strong><label><input type="checkbox" checked={c.active !== false} onChange={e => cert(c.id, { active: e.target.checked })}/> Show credential</label><label>Status<select className="admin-select" value={c.status || 'certified'} onChange={e => cert(c.id, { status: e.target.value, badge: e.target.value === 'certified' ? 'Certified' : 'In Progress' })}><option value="certified">Certified</option><option value="in-progress">In Progress</option></select></label><Field label="Credential ID" value={c.credentialId || ''} onChange={value => cert(c.id, { credentialId: value })}/>{c.status === 'in-progress' && <Field label="Study progress % (optional)" type="number" value={c.progress ?? ''} onChange={value => cert(c.id, { progress: value === '' ? null : Math.max(0, Math.min(100, +value)) })}/>}</div>)}</section>;
}
export function ProjectExtras({ project, update }: { project: any; update: (patch: any) => void }) {
  const nodes = project.architecture || [], metrics = project.metrics || [];
  return <details className="admin-project-extras"><summary>Flagship, demo links, architecture & metrics</summary><label className="admin-featured-check"><input type="checkbox" checked={!!project.featured} onChange={e => update({ featured: e.target.checked })}/> Feature in Recruiter Brief (first three in portfolio order)</label><div className="admin-form-grid"><Field label="Code / repository URL" value={project.codeUrl || ''} onChange={codeUrl => update({ codeUrl })}/><Field label="Live demo URL" value={project.demoUrl || ''} onChange={demoUrl => update({ demoUrl })}/></div><h4>Interactive architecture nodes</h4>{nodes.map((node: any, i: number) => <div className="admin-extra-row" key={node.id}><Field label={`Node ${i + 1}`} value={node.label} onChange={label => update({ architecture: nodes.map((n: any, j: number) => j === i ? { ...n, label } : n) })}/><Field label="Implementation detail" value={node.detail} onChange={detail => update({ architecture: nodes.map((n: any,j: number) => j === i ? { ...n, detail } : n) })}/><button className="admin-danger-btn" onClick={() => update({ architecture: nodes.filter((_: any,j: number) => j !== i) })}>Remove node</button></div>)}<button className="admin-secondary-btn" onClick={() => update({ architecture: [...nodes, { id: crypto.randomUUID(), label: 'New component', detail: '' }] })}>+ Architecture node</button><h4>Measured results</h4><p>Supply a source and measured value. Seeded projects do not claim live metrics.</p>{metrics.map((m: any,i: number) => <div className="admin-extra-row" key={i}>{['label','value','source','url'].map(key => <Field key={key} label={key === 'url' ? 'Evidence URL' : key} value={m[key] || ''} onChange={value => update({ metrics: metrics.map((entry: any,j: number) => j === i ? { ...entry, [key]: value } : entry) })}/>)}<button className="admin-danger-btn" onClick={() => update({ metrics: metrics.filter((_: any,j: number) => j !== i) })}>Remove metric</button></div>)}<button className="admin-secondary-btn" onClick={() => update({ metrics: [...metrics, { label: '', value: '', source: 'Project-reported', url: '' }] })}>+ Measured result</button></details>;
}
